notifications:
  email: false

sudo: required

services:
  - docker

env:
  global:
    - DOCKER_REPO=ivanilves

install:
  - docker pull ${DOCKER_REPO}/xiri-ubuntu
  - docker pull ${DOCKER_REPO}/xiri-centos

script:
  - testing/integration.sh zero
  - testing/integration.sh basic_connectivity_with_ssh
  - testing/integration.sh connect_with_ssh_agent
  - testing/integration.sh connect_with_ssh_key
  - testing/integration.sh do_client_teardown

branches:
  only:
    - master
